### ISSUE TITLE
dsbroker broken on windows x64

### ISSUE THREAD

**Issue by antowan** [IOT-DSA/broker-dart#4]
Hi Kenneth, 
As it seems I am not the only one concerned by this issue, I open a bug request here.
Windows version: windows_x64
Dart version: 1.16.1
broker-dart version: latest

Error message is the following :

_

> [INFO][DSA] Listening on HTTP port 8080
> Unhandled exception:
> SignalException: Failed to listen for SIGTERM, osError: OS Error: The operation completed successfully.
> , errno = 0
> # 0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:883)
> # 1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
> # 2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
> # 3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
> # 4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

_

**Comment by azenla** [comment]
Thanks, I have resolved the issue.
